security.protocol = SASL_SSL
sasl.mechanism = PLAIN
sasl.jaas.config = org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
ssl.truststore.type = PEM
ssl.truststore.location = certs/ca.crt
